name: safeway
description: "No description"
publish_to: 'none'
version: 1.1.2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.1.0
  geolocator: ^14.0.2
  flutter_riverpod: ^2.6.1
  go_router: ^16.3.0
  google_sign_in: ^7.2.0
  flutter_dotenv: ^6.0.0
  equatable: ^2.0.7
  sign_in_button: ^4.0.1
  shared_preferences: ^2.5.3
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster: ^8.2.2
  geocoding: ^4.0.0
  http: any
  intl: any
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  build_runner: ^2.4.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true
  assets:
    - .env